### ISSUE TITLE
where is pom.xml?

### ISSUE THREAD

**Issue by zak905** [jDramaix/jsinteropplayground#4]
it would be good if we can have the whole project so that we can directly clone it and build it.

**Comment by amirtoole** [comment]
I've forked this repo and setup the necessary gradle tasks to run super dev and deploy this demo.
Can be found here: https://github.com/hellofornow/AngularGwtExample/tree/gradleSupport
It's setup to use 2.8.0-SNAPSHOT, but you could change to pin to 2.8-beta1 if you'd like (may need some tweaks since JS_RC is no longer applicable).

**Comment by zak905** [comment]
great thanks. I will give it a try
